<style type = "text/css">


    a {
        color: #ffffff;
    }
    a:hover {
        color: #ffffff;
    }
    a:link {
        text-decoration: none;
    }
</style>


<div id="wrapper">


    <!-- Page Content -->
    <div id="page-content-wrapper">
        <!--<table id="myTable">-->
        <table id="">    
            <thead>
                <tr role="row">
                    <?php
                    foreach ($columns as $column) {
                        if ($order_by == $column['sort_name']) {
                            if ($order_n == 'DESC') {
                                $class = 'fa-sort-desc';
                                //$class = 'fa-sort-asc';
                            } else if ($order_n == 'ASC') {
                                $class = 'fa-sort-asc';
                                //$class = 'fa-sort-desc';
                            }
                        } else {
                            $class = 'fa-sort';
                        }
                        ?>

                        <th style="width: 50px;" >
                            <a href = "<?php echo $this->url("albumlisting", array('order_by' => $column['sort_name'], 'order' => $order)); ?>"><?php echo $column['title']?> <i class="fa <?php echo $class; ?>" aria-hidden="true"></i></a>
                        </th>
                    <?php } ?>

                </tr>
            </thead>
            <tbody>
                <?php foreach ($albums as $a) { ?>
                    <tr role="row" class="odd">
                        <!--<td align="center"><input type="checkbox" value = <?php //echo $usr['id'];         ?>></td>-->
                        <td><?php echo $a['id'] ?></td>
                        <td><?php echo $a['artist'] ?></td>
                        <td><?php echo $a['title'] ?></td>
                        <td><?php echo date('d-m-Y', strtotime($a['created_at'])); ?></td>
                    </tr>
                <?php } ?>

            </tbody>

        </table>
        

    </div>
    <!-- /#page-content-wrapper -->
</div>

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" />
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#myTable').DataTable();
    });
</script>
