

<div id="wrapper">
        <!-- Sidebar -->
        <?php echo $this->partial('menu_view', array('menu_item' => 'Archives', 'menu_array' => $menu)); ?>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="row">

                <div class="col-md-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><?php echo $this->translate('Previous Month 1') ?></h3>
                        </div>
                        <div class="panel-body">
                            <p><?php echo sprintf($this->translate('Previous Month 1 Listing')); ?></p>
                            <p><a class="btn btn-success pull-right" href="<?php echo $this->basePath("/timesheets/month/1"); ?>" target="_blank"><?php echo $this->translate('Previous Month 1') ?> &raquo;</a></p>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><?php echo $this->translate('Previous Month 2') ?></h3>
                        </div>
                        <div class="panel-body">
                            <p><?php echo sprintf($this->translate('Previous Month 1 Listing')) ?></p>
                            <p><a class="btn btn-success pull-right" href="<?php echo $this->basePath("/timesheets/month/2"); ?>" target="_blank"><?php echo $this->translate('Previous Month 2') ?> &raquo;</a></p>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><?php echo $this->translate('Previous Month 3') ?></h3>
                        </div>
                        <div class="panel-body">
                            <p><?php echo sprintf($this->translate('Previous Month 3 Listing')) ?></p>
                            <p><a class="btn btn-success pull-right" href="<?php echo $this->basePath("/timesheets/month/3"); ?>" target="_blank"><?php echo $this->translate('Previous Month 3') ?> &raquo;</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->
</div>





