<div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <span>Menu Options</span>
                </li>
                <li>
                    <a href="<?php echo $this->url('dashboard');?>">Dashboard</a>
                </li>
                <li class="active-selection">
                    <a href="<?php echo $this->url('currentmonth');?>">Present Month</a>
                </li>
                <li>
                    <a href="<?php echo $this->url('archives');?>">Archives</a>
                </li>
                <li>
                    <a href="<?php echo $this->url('statistics');?>">Statistics</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <table>
                <th style="width: 150px;" >Date</th>
                <th style="width: 150px;" >Time In</th>
                <th style="width: 150px;" >Time Out</th>
                <th style="width: 150px;" >Actions</th>

                <tr>
                    <td>17-10-1992</td>
                    <td>09:00 Hrs</td>
                    <td></td>
                    <td>actions indeed!</td>
                </tr>
            </table>
        </div>
        <!-- /#page-content-wrapper -->
</div>
