<style>
    .clock-in-button {
        background-color: #3B6AA0; 
        border: 0;
        color: #FFFFFF;
        font-weight: bold;
        padding: 10px 20px; 
    }

    .clock-in-button:hover {
        background: #1E90FF; /* Dodger Blue */
        color: #FFFFFF;
        text-decoration: none;  
    }
    
    .clock-container {
    background-color: lightgrey;
    width: 300px;
    border: none;
    padding: 25px;
    margin: 25px;
    float: right;
    
    
    
}
</style>

<div id="wrapper">
        <!-- Sidebar -->
        <?php echo $this->partial('menu_view', array('menu_item' => 'Dashboard', 'menu_array' => $menu)); ?>
        <!-- /#sidebar-wrapper -->
        <div class="jumbotron">
            <!--<a class="clock-in-button" href="">Check In</a>-->
            <div class="clock-container">
                
            </div>
            
            
            
        </div>

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="row">

                <div class="col-md-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><?php echo $this->translate('Current Month') ?></h3>
                        </div>
                        <div class="panel-body">
                            <p><?php echo sprintf($this->translate('Current Month Listing')); ?></p>
                            <p><a class="btn btn-success pull-right" href="" target="_blank"><?php echo $this->translate('Current Month') ?> &raquo;</a></p>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><?php echo $this->translate('Archives') ?></h3>
                        </div>
                        <div class="panel-body">
                            <p><?php echo sprintf($this->translate('View Archives')) ?></p>
                            <p><a class="btn btn-success pull-right" href="" target="_blank"><?php echo $this->translate('Archives') ?> &raquo;</a></p>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><?php echo $this->translate('Statistics') ?></h3>
                        </div>
                        <div class="panel-body">
                            <p><?php echo sprintf($this->translate('View Statistics')) ?></p>
                            <p><a class="btn btn-success pull-right" href="" target="_blank"><?php echo $this->translate('Statistics') ?> &raquo;</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->
</div>





