<?php if ($this->pageCount): ?>
<div>
    <ul class="pagination pull-right">
        <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
            <a href="<?php echo $this->url('currentmonth', array('page' => $this->first, 'order_by' => $order_by, 'order' => $order)); ?>">First</a></li>
        <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
            <a href="<?php echo $this->url('currentmonth', array('page' => $this->previous, 'order_by' => $order_by, 'order' => $order)); ?>">Previous</a></li>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <li <?php echo $page == $this->current ? 'class="active"' : ''; ?>><a href="<?php echo $this->url('currentmonth', array('page' => $page, 'order_by' => $order_by, 'order' => $order)); ?>">
                    <?php echo $page; ?>
                </a></li>
        <?php endforeach; ?>

        <!-- Next page link -->
        <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
            <a href="<?php echo $this->url('currentmonth', array('page' => $this->next,  'order_by' => $order_by, 'order' => $order)); ?>">Next</a></li>
        <!-- Last page link -->
        <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
            <a href="<?php echo $this->url('currentmonth', array('page' => $this->last,  'order_by' => $order_by, 'order' => $order)); ?>">Last</a></li>
    </ul>
</div>
    
<?php endif; ?>