<!--<div class="jumbotron">
    <img style="width:1000px;height:300px;" src="/img/hendrix.jpg">
</div>
-->
<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Time Sheets') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('View Time Sheets')); ?></p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url("currentmonth"); ?>" target="_blank"><?php echo $this->translate('Time Sheets') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Music') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('View Music')) ?></p>
                <p><a class="btn btn-success pull-right" href="" target="_blank"><?php echo $this->translate('Music') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('TV Shows') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('View TV Shows')) ?></p>
                <p><a class="btn btn-success pull-right" href="" target="_blank"><?php echo $this->translate('TV Shows') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Books') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('View Books')) ?></p>
                <p><a class="btn btn-success pull-right" href="" target="_blank"><?php echo $this->translate('Books') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Movies') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Movies')) ?></p>
                <p><a class="btn btn-success pull-right" href="" target="_blank"><?php echo $this->translate('Movies') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Anime') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Anime')) ?></p>
                <p><a class="btn btn-success pull-right" href="" target="_blank"><?php echo $this->translate('Anime') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    
</div>
